name: alias_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.5.0

environment:
  sdk: ^3.8.1

dependencies:
  system_command_runner: ^0.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
